[tool.poetry]
name = "slack-ai-agent-starter"
version = "0.1.0"
description = "Slack AI Agent Starter Kit"
authors = ["kyaukyuai <y.kakui@gmail.com>"]
readme = "README.md"
repository = "https://github.com/kyaukyuai/slack-ai-agent-starter"
keywords = ["slack", "ai", "bot", "langchain"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.11",
]
package-mode = false
packages = [
    { include = "slack_ai_agent", from = "." }
]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
slack-bolt = "^1.22.0"
python-dotenv = "^1.0.1"
langchain_anthropic = ">=0.1.0,<0.2.0"
langchain_core = ">=0.2.0,<0.3.0"
langchain_openai = ">=0.1.0,<0.2.0"
langchain_community = ">=0.2.0,<0.3.0"
langgraph-sdk = "^0.1.48"
tavily-python = "^0.3.0"
hupper = "^1.12.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.2"
pre-commit = "^4.1.0"
mypy = "^1.14.1"
langgraph-cli = {extras = ["inmem"], version = "^0.1.65"}

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.mypy]
python_version = "3.12"
disallow_untyped_defs = false  # Slackのデコレータがuntypedなため
disallow_incomplete_defs = false  # デコレータの関係で緩和
check_untyped_defs = true
disallow_untyped_decorators = false  # Slack-boltのデコレータを許可
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = false  # type: ignoreコメントのチェックを無効化
warn_return_any = false  # Any型の返値を許可
warn_unreachable = false  # 到達不能コードの警告を無効化
ignore_missing_imports = true  # 外部パッケージの型ヒントがない場合を許可
allow_untyped_calls = true  # 型付けされていない関数呼び出しを許可
follow_imports = "skip" # importエラーを全て無視する
ignore_errors = true      # すべての型チェックエラーを無視

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
