[tool.poetry]
name = "slack-ai-agent-starter"
version = "0.1.0"
description = ""
authors = ["kyaukyuai <y.kakui@gmail.com>"]
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = ">=3.11,<4.0"
slack-bolt = "^1.22.0"
python-dotenv = "^1.0.1"
langchain_anthropic = "^0.1.0"
langchain_core = "^0.2.0"
langchain_openai = "^0.1.0"
langchain_community = "^0.2.0"
langgraph-sdk = "^0.1.48"
tavily-python = "^0.3.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.2"
pre-commit = "^4.1.0"
mypy = "^1.14.1"
langgraph-cli = {extras = ["inmem"], version = "^0.1.65"}
honcho = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
